apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-label
  labels:
    team: finance
    version: 1.4.8
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
