apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-annotation
  labels:
    team: engineer
    version: 1.0.2
    environment: development
  annotations:
    description: Ini adalah aplikasi yang dibuat oleh tim engineer
    sub_title: Apapun itu....
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
